#!/sbin/busybox sh

# write log to kmsg
log() {
	echo "[wantguns' tiny linux]: $@" > /dev/kmsg
}

die() {
    log FATAL: $@

    # Don't exit or else the kernel will panic
    sleep 99999999
}

# Populate initramfs
/sbin/busybox --install -s 

mount -t proc none /proc    || die Could not mount /proc
mount -t sysfs none /sys    || die Could not mount /sys
mount -t devtmpfs none /dev || die Could not mount /dev

log 
log We are up
log

# /bin/sh is our init \o/
exec /bin/sh
